
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mantenimiento.Mantenimiento;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author soul
 */
public class FrmMantenimientos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMantenimientos.class.getName());

    /**
     * Creates new form FrmMantenimientos
     */
    
    private final ArrayList<Mantenimiento> listaMantenimientos = new ArrayList<>();
    private DefaultTableModel modeloTabla;
    
    public FrmMantenimientos() {
        initComponents();
        configurarTabla();
        cargarTabla();
    }
    
    private void configurarTabla() {
        modeloTabla = new DefaultTableModel(
            new Object[]{"Equipo", "Técnico", "Fecha", "Tipo", "Estado"}, 0
        );
        tblMantenimientos.setModel(modeloTabla);
    }
    
    private void cargarTabla() {
        modeloTabla.setRowCount(0); // Limpia duplicados
        for (Mantenimiento m : listaMantenimientos) {
            modeloTabla.addRow(new Object[]{
                m.getEquipo(),
                m.getTecnico(),
                m.getFecha(),
                m.getTipoMantenimiento(),
                m.getEstado()
            });
        }
    }
    
    private void limpiarCampos() {
        txtEquipo.setText("");
        txtTecnico.setText("");
        txtFecha.setText("");
        grupoTipo.clearSelection();
        grupoEstado.clearSelection();
    }

    private void agregarMantenimiento() {
        String equipo = txtEquipo.getText().trim();
        String tecnico = txtTecnico.getText().trim();
        String fecha = txtFecha.getText().trim();

        // Validar campos de texto vacíos
        if (equipo.isEmpty() || tecnico.isEmpty() || fecha.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe completar todos los campos de texto.");
            return;
        }

        // Obtener selección de Tipo de Mantenimiento
        String tipo;
        if (rbtnPreventivo.isSelected()) {
            tipo = "Preventivo";
        } else if (rbtnCorrectivo.isSelected()) {
            tipo = "Correctivo";
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione el tipo de mantenimiento.");
            return;
        }

        // Obtener selección de Estado
        String estado;
        if (rbtnRealizado.isSelected()) {
            estado = "Realizado";
        } else if (rbtnPendiente.isSelected()) {
            estado = "Pendiente";
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione el estado del mantenimiento.");
            return;
        }

        // Crear objeto, guardar en memoria y refrescar tabla
        Mantenimiento nuevo = new Mantenimiento(equipo, tecnico, fecha, tipo, estado);
        listaMantenimientos.add(nuevo);
        cargarTabla();
        limpiarCampos();
        JOptionPane.showMessageDialog(this, "Mantenimiento registrado con éxito.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTipo = new javax.swing.ButtonGroup();
        grupoEstado = new javax.swing.ButtonGroup();
        txtEquipo = new javax.swing.JTextField();
        txtTecnico = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        rbtnPreventivo = new javax.swing.JRadioButton();
        rbtnCorrectivo = new javax.swing.JRadioButton();
        rbtnRealizado = new javax.swing.JRadioButton();
        rbtnPendiente = new javax.swing.JRadioButton();
        btnAgregar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMantenimientos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        grupoTipo.add(rbtnPreventivo);
        rbtnPreventivo.setText("Preventivo");

        grupoTipo.add(rbtnCorrectivo);
        rbtnCorrectivo.setText("Correctivo");

        grupoEstado.add(rbtnRealizado);
        rbtnRealizado.setText("Realizado");

        grupoEstado.add(rbtnPendiente);
        rbtnPendiente.setText("Pendiente");

        btnAgregar.setText("Registrar Mantenimiento");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        btnLimpiar.setText("Limpiar Campos");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        tblMantenimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMantenimientos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(txtTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnPendiente)
                                    .addComponent(rbtnCorrectivo)
                                    .addComponent(rbtnPreventivo)
                                    .addComponent(rbtnRealizado)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(btnAgregar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpiar)
                        .addGap(27, 27, 27)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtnPreventivo))
                        .addGap(52, 52, 52)
                        .addComponent(rbtnCorrectivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(rbtnRealizado)
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtnPendiente))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        agregarMantenimiento();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMantenimientos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.ButtonGroup grupoEstado;
    private javax.swing.ButtonGroup grupoTipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtnCorrectivo;
    private javax.swing.JRadioButton rbtnPendiente;
    private javax.swing.JRadioButton rbtnPreventivo;
    private javax.swing.JRadioButton rbtnRealizado;
    private javax.swing.JTable tblMantenimientos;
    private javax.swing.JTextField txtEquipo;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtTecnico;
    // End of variables declaration//GEN-END:variables
}
