package mantenimiento;


import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import usuarioo.FrmLogin;
import usuarioo.Usuarioo.Usuario;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author soul
 */
public class FrmMantenimientos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMantenimientos.class.getName());

    /**
     * Creates new form FrmMantenimientos
     */
    
    private final ArrayList<Mantenimiento> listaMantenimientos = new ArrayList<>();
    private DefaultTableModel modeloTabla;
    private final Usuario usuarioActual;

    public FrmMantenimientos(Usuario usuarioActual) {
        initComponents();
        this.usuarioActual = usuarioActual;
        configurarTabla();
        cargarTabla();
        jLabel4.setText("INFORME DE MANTENIMIENTO - " + usuarioActual.getUser());
        btnCerrar.setText("Cerrar sesion (" + usuarioActual.getUser() + ")");
    }
    
    private void configurarTabla() {
        modeloTabla = new DefaultTableModel(
            new Object[]{"Equipo", "Técnico", "Fecha", "Tipo", "Estado"}, 0
        );
        tblMantenimientos.setModel(modeloTabla);
    }
    
    private void cargarTabla() {
        modeloTabla.setRowCount(0); 
        for (Mantenimiento m : listaMantenimientos) {
            modeloTabla.addRow(new Object[]{
                m.getEquipo(),
                m.getTecnico(),
                m.getFecha(),
                m.getTipoMantenimiento(),
                m.getEstado()
            });
        }
    }
    
    private void limpiarCampos() {
        txtEquipo.setText("");
        txtTecnico.setText("");
        txtFecha.setText("");
        txtCosto.setText("");
        grupoTipo.clearSelection();
        grupoEstado.clearSelection();
        
    }

    private void agregarMantenimiento() {
        String equipo = txtEquipo.getText().trim();
        String tecnico = txtTecnico.getText().trim();
        String fecha = txtFecha.getText().trim();

        if (equipo.isEmpty() || tecnico.isEmpty() || fecha.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe completar todos los campos de texto.");
            return;
        }

        String tipo;
        if (rbtnPreventivo.isSelected()) {
            tipo = "Preventivo";
        } else if (rbtnCorrectivo.isSelected()) {
            tipo = "Correctivo";
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione el tipo de mantenimiento.");
            return;
        }

        String estado;
        if (rbtnRealizado.isSelected()) {
            estado = "Realizado";
        } else if (rbtnPendiente.isSelected()) {
            estado = "Pendiente";
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione el estado del mantenimiento.");
            return;
        }
        
        String textoCosto = txtCosto.getText().trim().replace(",", ".");
        if (textoCosto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe completar el campo Costo.");
            return;
        }

        double costo;
        try {
            costo = Double.parseDouble(textoCosto);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El Costo debe ser un número. Ejemplo: 150.50");
            return;
        }

        if (costo < 0) {
            JOptionPane.showMessageDialog(this, "El Costo no puede ser negativo.");
            return;
        }

        Mantenimiento nuevo = new Mantenimiento(equipo, tecnico, fecha, tipo, estado, costo);
        listaMantenimientos.add(nuevo);
        cargarTabla();
        limpiarCampos();
        JOptionPane.showMessageDialog(this, "Mantenimiento registrado con éxito.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTipo = new javax.swing.ButtonGroup();
        grupoEstado = new javax.swing.ButtonGroup();
        txtEquipo = new javax.swing.JTextField();
        txtTecnico = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        rbtnPreventivo = new javax.swing.JRadioButton();
        rbtnCorrectivo = new javax.swing.JRadioButton();
        rbtnRealizado = new javax.swing.JRadioButton();
        rbtnPendiente = new javax.swing.JRadioButton();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMantenimientos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        btnInforme = new javax.swing.JButton();
        btnInformeTecnico = new javax.swing.JButton();
        btnInformeCostos = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        grupoTipo.add(rbtnPreventivo);
        rbtnPreventivo.setText("Preventivo");

        grupoTipo.add(rbtnCorrectivo);
        rbtnCorrectivo.setText("Correctivo");

        grupoEstado.add(rbtnRealizado);
        rbtnRealizado.setText("Realizado");

        grupoEstado.add(rbtnPendiente);
        rbtnPendiente.setText("Pendiente");

        btnAgregar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnAgregar.setText("Registrar Mantenimiento");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        tblMantenimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMantenimientos);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel1.setText("Equipo");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel2.setText("Tecnico");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel3.setText("Fecha");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel4.setText("INFORME DE MANTENIMIENTO");

        btnCerrar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnCerrar.setText("Cerrar sesion");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        btnInforme.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnInforme.setText("Ver Pendientes");
        btnInforme.addActionListener(this::btnInformeActionPerformed);

        btnInformeTecnico.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnInformeTecnico.setText("Informe por Técnico");
        btnInformeTecnico.addActionListener(this::btnInformeTecnicoActionPerformed);

        btnInformeCostos.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnInformeCostos.setText("Informe de Costos");
        btnInformeCostos.addActionListener(this::btnInformeCostosActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel5.setText("Costo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtFecha)
                                        .addComponent(txtTecnico)
                                        .addComponent(txtEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnPendiente)
                                    .addComponent(rbtnRealizado)
                                    .addComponent(rbtnCorrectivo)
                                    .addComponent(rbtnPreventivo))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnInforme)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnInformeTecnico)
                                .addGap(63, 63, 63)
                                .addComponent(btnInformeCostos))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrar)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 36, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnInformeCostos)
                                .addComponent(btnInformeTecnico))
                            .addComponent(btnInforme))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtnPreventivo))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(rbtnCorrectivo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(rbtnRealizado)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbtnPendiente)
                                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(54, 54, 54)))
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        agregarMantenimiento();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Desea cerrar la sesión de " + usuarioActual.getUser() + "?",
                "Cerrar sesión",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (opcion == JOptionPane.YES_OPTION) {
            this.dispose();
            new FrmLogin().setVisible(true);
        }
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformeActionPerformed
        // TODO add your handling code here:
        FrmInformePendientes informe = new FrmInformePendientes(this.listaMantenimientos);
        informe.setVisible(true);
    }//GEN-LAST:event_btnInformeActionPerformed

    private void btnInformeTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformeTecnicoActionPerformed
        // TODO add your handling code here:
        FrmInformeTecnico informeTec = new FrmInformeTecnico(this.listaMantenimientos);
        informeTec.setVisible(true);
    }//GEN-LAST:event_btnInformeTecnicoActionPerformed

    private void btnInformeCostosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformeCostosActionPerformed
        // TODO add your handling code here:
        FrmInformeCostos informeCostos = new FrmInformeCostos(this.listaMantenimientos);
        informeCostos.setVisible(true);
    }//GEN-LAST:event_btnInformeCostosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new FrmMantenimientos(new Usuario(1, "DANIEL", "7612", 1)).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnInforme;
    private javax.swing.JButton btnInformeCostos;
    private javax.swing.JButton btnInformeTecnico;
    private javax.swing.ButtonGroup grupoEstado;
    private javax.swing.ButtonGroup grupoTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtnCorrectivo;
    private javax.swing.JRadioButton rbtnPendiente;
    private javax.swing.JRadioButton rbtnPreventivo;
    private javax.swing.JRadioButton rbtnRealizado;
    private javax.swing.JTable tblMantenimientos;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtEquipo;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtTecnico;
    // End of variables declaration//GEN-END:variables
}
